apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mailing-microservice
spec:
  selector:
    matchLabels:
      app: mailing-microservice
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mailing-microservice
    spec:
      containers:
        - name: mailing-microservice
          image: mailing-microservice:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster